server:
  port: 0

spring:
  application:
    name: streaming-service

  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.example.client.UserServiceClient: DEBUG
    feign: DEBUG

token:
  secret: "A9F2C3E4B5D6A7F8G9H0J1K2L3M4N5O6A9F2C3E4B5D6A7F8G9H0J1K2L3M4N5O6"
